SELECT b.CATEGORY, sum(bs.TOTAL_SALES) as TOTAL_SALES
FROM BOOK b, (
    SELECT BOOK_ID, sum(SALES) TOTAL_SALES
    FROM BOOK_SALES
    WHERE SALES_DATE like '2022-01%'
    GROUP BY BOOK_ID
    ) bs
WHERE b.BOOK_ID = bs.BOOK_ID
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY

    